language: python
python:
  - "3.6.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
#command to configure notifications
notifications:
  email:
    on_success: change
# command to run tests
script: 
  nosetests --with-coverage --cover-package=tests && coverage report
after_success:
  coveralls